export const initialState = {
	fields: {
		cpf: '',
		fullName: '',
		socialName: '',
		phone: '',
		email: '',
		coupon: '',
		hasSocialName: false,
		acceptTerms: false,
		mktCommunication: false,
	},
	url: '',
	reminderList: [],
	rescheduling: [],
	isEnableSubmitButton: false,
	isEnableModalButton: false,
	isLoadingRescheduling: false,
	isShowModalRescheduling: false,
	isLoadingPricing: false,
	refusedOption: false,
	isOpenDialog: false,
	isOpenModal: false,
	isOpenDialogError: false,
	isLoading: false,
	isLoadingRetryProposal: false,
	isLoadingPhone: false,
	isLoadingEmail: false,
	isLoadingSocialName: false,
	isValidCoupon: false,
	selectedReschedulingDate: {
		day: '',
		weekday: '',
		month: '',
		schedules: [],
		setDateTime: '',
		selected: false,
	},
	errors: {},
	requestStatus: {
		success: false,
		message: '',
		feedback: '',
	},
};
